spring:
  application:
    name: hello-security  # 应用名称
  security:
    user:
      name: admin  # 配置的security用户名，默认：user
      password: password  # 配置security密码，默认：随机生成的字符串，名文配置的密码替换加密格式去配置改动默认登录去解码 留个家庭作业！
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpledemo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
server:
  port: 8001  # 端口
  servlet:
    context-path: /demo  # thymeleaf映射相对路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.oauth2securitydemo.entities
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.atguigu: debug