spring:
  application:
    name: hello-security  # 应用名称
  security:
    user:
      name: admin  # security用户名
      password: 123  # security密码
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpledemo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
server:
  port: 8001  # 端口
  servlet:
    context-path: /demo  # thymeleaf映射相对路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.oauth2securitydemo.entities
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.atguigu: debug