spring:
  application:
    name: oauth2-login  # 应用名称
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6ef17d582ff386565b59  # github授权服务的client_id
            client-secret: 1863e5ca30c3a1c7aca20a06564716c269163fa5  # github的client_secret
server:
  port: 8002
#  servlet:
#    context-path: /oauth2  # thymeleaf映射相对路径 默认不可以加相对路径，github这个授权服务器的redirect_url=http://ip:port/login/oauth2/code/github
logging:
  level:
    com.atguigu: debug